name: Adam Pash
description: Writings about things
url: http://adampash.com
highlighter: pygments

kramdown:
  input: GFM

permalink: /:title

timezone: America/New_York

include: [feed, .well-known/acme-challenge/RwAkBf87N7ypJlM4XUHIwO704mEkaYekOB3-iW2xSsQ]
