source 'https://rubygems.org'

gem 'github-pages'
gem 'jekyll'
gem 'kramdown'
gem 'pygments.rb'

group :development do
  gem 'rake'
  gem 'guard'
  gem 'coffee-script'
  gem 'guard-coffeescript'
  gem 'rb-fsevent'
  gem 'rb-inotify'
  gem 'compass'
  gem 'sass'
  gem 'guard-compass'
  gem 'guard-process'
  gem 'guard-livereload'
  gem 'uglifier'
  gem 'juicer'
  gem 'guard-uglify'
  gem 'libv8', '3.16.14.7'
  gem 'therubyracer', '0.12.2'
end
